-- general configuration
require('config/keymap')
require('config/colorscheme')
-- plugins
require('plugins')
require('plugins/nvim-tree')
require('plugins/syntax-highlight')
require('plugins/mason')
require('plugins/completions')
require('plugins/statusbar')
require('plugins/lsps/lua')
require('plugins/lsps/clangd')
require('plugins/lsps/dockerfile')
require('plugins/lsps/rustanalyzer')
require('plugins/lspsaga')
require('plugins/file-finder')
require('plugins/autopairs')
require('plugins/gitsigns')
